// Database Types for BRUTAL NOTES

export interface Todo {
  id?: number // Auto-generated by Dexie
  text: string
  completed: boolean
  createdAt: Date
  updatedAt: Date
  syncStatus: 'pending' | 'synced' | 'error' // For future sync functionality
}

export interface Note {
  id?: number // Auto-generated by Dexie
  title: string
  content: string // JSON string from Lexical editor
  path: string // File path in the tree structure
  createdAt: Date
  updatedAt: Date
  syncStatus: 'pending' | 'synced' | 'error' // For future sync functionality
  isFolder: boolean
  parentId?: number // For nested folder structure
}

export interface FileNode {
  id: string
  name: string
  type: 'file' | 'folder'
  noteId?: number // Links to Note in database
  children?: FileNode[]
  expanded?: boolean
}

// Database operations result types
export interface DatabaseResult<T> {
  success: boolean
  data?: T
  error?: string
}

export type SyncStatus = 'pending' | 'synced' | 'error'
