// Database Types for BRUTAL NOTES

export interface Todo {
  id?: number // Auto-generated by Dexie (local ID)
  serverId?: string // UUID from backend server
  clientId?: string // Stable app-level identifier used for sync
  text: string
  completed: boolean
  sourceNoteClientId?: string // Local-first backlink to the originating note
  sourceNoteTitle?: string // Snapshot used for compact UI badges
  deleted?: boolean // Soft delete flag for sync purposes
  version: number // Version for conflict resolution
  createdAt: Date
  updatedAt: Date
  syncStatus: 'pending' | 'synced' | 'error' // For sync functionality
  lastSyncAt?: Date // Track when this item was last synced
}

export interface Note {
  id?: number // Auto-generated by Dexie (local ID)
  serverId?: string // UUID from backend server
  clientId?: string // Stable app-level identifier used for sync
  title: string
  content: string // JSON string from Lexical editor
  path?: string // Denormalized logical path used for sync and hierarchy operations
  createdAt: Date
  updatedAt: Date
  syncStatus: 'pending' | 'synced' | 'error' // For sync functionality
  isFolder: boolean
  parentId?: number // For nested folder structure (local)
  serverParentId?: string // UUID of parent on server
  parentClientId?: string // Changed to string for consistency
  deleted?: boolean // Soft delete flag for sync purposes
  version: number // Version for conflict resolution
  lastSyncAt?: Date // Track when this item was last synced
}

export interface FileNode {
  id: string
  name: string
  type: 'file' | 'folder'
  noteId?: number // Links to Note in database (still uses local Dexie ID)
  children?: FileNode[]
  expanded?: boolean
}

// Database operations result types
export interface DatabaseResult<T> {
  success: boolean
  data?: T
  error?: string
}

export type SyncStatus = 'pending' | 'synced' | 'error'
