// Database Types for BRUTAL NOTES

export interface Todo {
  id?: number // Auto-generated by Dexie (local ID)
  serverId?: string // UUID from backend server
  clientId?: number // For bulk sync mapping (uses local Dexie ID)
  text: string
  completed: boolean
  deleted?: boolean // Soft delete flag for sync purposes
  createdAt: Date
  updatedAt: Date
  syncStatus: 'pending' | 'synced' | 'error' // For sync functionality
}

export interface Note {
  id?: number // Auto-generated by Dexie (local ID)
  serverId?: string // UUID from backend server
  clientId?: number // For bulk sync mapping (uses local Dexie ID)
  title: string
  content: string // JSON string from Lexical editor
  path: string // File path in the tree structure
  createdAt: Date
  updatedAt: Date
  syncStatus: 'pending' | 'synced' | 'error' // For sync functionality
  isFolder: boolean
  parentId?: number // For nested folder structure (local)
  serverParentId?: string // UUID of parent on server
  deleted?: boolean // Soft delete flag for sync purposes
}

export interface FileNode {
  id: string
  name: string
  type: 'file' | 'folder'
  noteId?: number // Links to Note in database
  children?: FileNode[]
  expanded?: boolean
}

// Database operations result types
export interface DatabaseResult<T> {
  success: boolean
  data?: T
  error?: string
}

export type SyncStatus = 'pending' | 'synced' | 'error'
